// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: ap.proto

package pb

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApClient is the client API for Ap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApClient interface {
	Notify(ctx context.Context, in *ApNotifyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type apClient struct {
	cc grpc.ClientConnInterface
}

func NewApClient(cc grpc.ClientConnInterface) ApClient {
	return &apClient{cc}
}

func (c *apClient) Notify(ctx context.Context, in *ApNotifyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/saga.Ap/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApServer is the server API for Ap service.
// All implementations must embed UnimplementedApServer
// for forward compatibility
type ApServer interface {
	Notify(context.Context, *ApNotifyRequest) (*empty.Empty, error)
	mustEmbedUnimplementedApServer()
}

// UnimplementedApServer must be embedded to have forward compatible implementations.
type UnimplementedApServer struct {
}

func (UnimplementedApServer) Notify(context.Context, *ApNotifyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedApServer) mustEmbedUnimplementedApServer() {}

// UnsafeApServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApServer will
// result in compilation errors.
type UnsafeApServer interface {
	mustEmbedUnimplementedApServer()
}

func RegisterApServer(s grpc.ServiceRegistrar, srv ApServer) {
	s.RegisterService(&Ap_ServiceDesc, srv)
}

func _Ap_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/saga.Ap/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApServer).Notify(ctx, req.(*ApNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ap_ServiceDesc is the grpc.ServiceDesc for Ap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saga.Ap",
	HandlerType: (*ApServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Ap_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ap.proto",
}
