{
 "title": "dtx TC",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "total transaction 24h (SAGA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(dtx_tc_txn_h_count{type=\"saga\"}[1d]))"
    }
   ]
  },
  {
   "title": "total transaction 24h (TCC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(dtx_tc_txn_h_count{type=\"tcc\"}[1d]))"
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transaction QPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_txn_h_count[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Transaction QPS with result",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_txn_h_count[1m])) by (instance, type, ret)",
       "legendFormat": "{{instance}} - {{type}} - {{ret}}"
      }
     ]
    },
    {
     "title": "Transaction lifetime mean",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_txn_h_sum[1m])) by (type, ret) / sum(rate(dtx_tc_txn_h_count[1m])) by (type, ret)",
       "legendFormat": "{{type}} - {{ret}}"
      }
     ]
    },
    {
     "title": "Transaction lifetime P90",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,sum(rate(dtx_tc_txn_h_bucket{}[30s])) by (le, type, ret))",
       "legendFormat": "{{type}} - {{ret}}"
      }
     ]
    },
    {
     "title": "Transaction lifetime P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(dtx_tc_txn_h_bucket{}[30s])) by (le, type, ret))",
       "legendFormat": "{{type}} - {{ret}}"
      }
     ]
    },
    {
     "title": "Process QPS",
     "type": "timeseries",
     "description": "QPS of Process transaction including retry",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_process_h_count[1m])) by (instance, type, op)",
       "legendFormat": "{{instance}} - {{type}} - {{op}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Branch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Branch QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_branch_h_count[1m])) by (type, branch)",
       "legendFormat": "{{type}} - {{branch}}"
      }
     ]
    },
    {
     "title": "Branch duration (mean)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_branch_h_sum[1m])) by (type, branch) / sum(rate(dtx_tc_branch_h_count[1m])) by (type, branch)",
       "legendFormat": "{{type}} - {{branch}}"
      }
     ]
    },
    {
     "title": "Branch duration (P90)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,sum(rate(dtx_tc_branch_h_bucket{}[30s])) by (le, type, branch))",
       "legendFormat": "{{type}} - {{branch}}"
      }
     ]
    },
    {
     "title": "Branch duration (P99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(dtx_tc_branch_h_bucket{}[30s])) by (le, type, branch))",
       "legendFormat": "{{type}} - {{branch}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "database QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_saga_model_h_count[1m])) by (op, ret)",
       "legendFormat": "{{op}} - {{ret}}"
      }
     ]
    },
    {
     "title": "database operation duration (mean)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_saga_model_h_sum[1m])) by (op, ret) / sum(rate(dtx_tc_saga_model_h_count[1m])) by (op, ret)",
       "legendFormat": "{{op}} - {{ret}}"
      }
     ]
    },
    {
     "title": "database operation duration (P90)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9,sum(rate(dtx_tc_saga_model_h_bucket{}[30s])) by (le, op, ret))",
       "legendFormat": "{{op}} - {{ret}}"
      }
     ]
    },
    {
     "title": "database operation duration (P99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,sum(rate(dtx_tc_saga_model_h_bucket{}[30s])) by (le, op, ret))",
       "legendFormat": "{{op}} - {{ret}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "SAGA request QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_saga_request_h_count[1m])) by (protocol, op, code)",
       "legendFormat": "{{protocol}}-{{op}}-{{code}}"
      }
     ]
    },
    {
     "title": "TCC request QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(dtx_tc_tcc_request_h_count[1m])) by (protocol, op, code)",
       "legendFormat": "{{protocol}}-{{op}}-{{code}}"
      }
     ]
    }
   ]
  }
 ]
}