// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.6.1
// source: saga_bank.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SagaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account int32 `protobuf:"varint,2,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *SagaRequest) Reset() {
	*x = SagaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaRequest) ProtoMessage() {}

func (x *SagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_saga_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaRequest.ProtoReflect.Descriptor instead.
func (*SagaRequest) Descriptor() ([]byte, []int) {
	return file_saga_bank_proto_rawDescGZIP(), []int{0}
}

func (x *SagaRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SagaRequest) GetAccount() int32 {
	if x != nil {
		return x.Account
	}
	return 0
}

type SagaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SagaResponse) Reset() {
	*x = SagaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_saga_bank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaResponse) ProtoMessage() {}

func (x *SagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_saga_bank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaResponse.ProtoReflect.Descriptor instead.
func (*SagaResponse) Descriptor() ([]byte, []int) {
	return file_saga_bank_proto_rawDescGZIP(), []int{1}
}

var File_saga_bank_proto protoreflect.FileDescriptor

var file_saga_bank_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x61, 0x67, 0x61, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x40,
	0x0a, 0x0b, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x32, 0x8c, 0x01, 0x0a, 0x0f, 0x53, 0x61, 0x67, 0x61, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x02, 0x49, 0x6e, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x6e,
	0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x03, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x61, 0x6e, 0x6b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x61, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_saga_bank_proto_rawDescOnce sync.Once
	file_saga_bank_proto_rawDescData = file_saga_bank_proto_rawDesc
)

func file_saga_bank_proto_rawDescGZIP() []byte {
	file_saga_bank_proto_rawDescOnce.Do(func() {
		file_saga_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_saga_bank_proto_rawDescData)
	})
	return file_saga_bank_proto_rawDescData
}

var file_saga_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_saga_bank_proto_goTypes = []interface{}{
	(*SagaRequest)(nil),  // 0: bankservice.SagaRequest
	(*SagaResponse)(nil), // 1: bankservice.SagaResponse
}
var file_saga_bank_proto_depIdxs = []int32{
	0, // 0: bankservice.SagaBankService.In:input_type -> bankservice.SagaRequest
	0, // 1: bankservice.SagaBankService.Out:input_type -> bankservice.SagaRequest
	1, // 2: bankservice.SagaBankService.In:output_type -> bankservice.SagaResponse
	1, // 3: bankservice.SagaBankService.Out:output_type -> bankservice.SagaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saga_bank_proto_init() }
func file_saga_bank_proto_init() {
	if File_saga_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_saga_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SagaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_saga_bank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SagaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_saga_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_saga_bank_proto_goTypes,
		DependencyIndexes: file_saga_bank_proto_depIdxs,
		MessageInfos:      file_saga_bank_proto_msgTypes,
	}.Build()
	File_saga_bank_proto = out.File
	file_saga_bank_proto_rawDesc = nil
	file_saga_bank_proto_goTypes = nil
	file_saga_bank_proto_depIdxs = nil
}
